/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "db-message.protoc.pb-c.h"
void   sds_metadata_db_key__init
                     (SDSMetadataDbKey         *message)
{
  static SDSMetadataDbKey init_value = SDS_METADATA_DB_KEY__INIT;
  *message = init_value;
}
size_t sds_metadata_db_key__get_packed_size
                     (const SDSMetadataDbKey *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sds_metadata_db_key__pack
                     (const SDSMetadataDbKey *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sds_metadata_db_key__pack_to_buffer
                     (const SDSMetadataDbKey *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SDSMetadataDbKey *
       sds_metadata_db_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SDSMetadataDbKey *)
     protobuf_c_message_unpack (&sds_metadata_db_key__descriptor,
                                allocator, len, data);
}
void   sds_metadata_db_key__free_unpacked
                     (SDSMetadataDbKey *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sds_file__init
                     (SdsFile         *message)
{
  static SdsFile init_value = SDS_FILE__INIT;
  *message = init_value;
}
size_t sds_file__get_packed_size
                     (const SdsFile *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_file__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sds_file__pack
                     (const SdsFile *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_file__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sds_file__pack_to_buffer
                     (const SdsFile *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_file__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SdsFile *
       sds_file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SdsFile *)
     protobuf_c_message_unpack (&sds_file__descriptor,
                                allocator, len, data);
}
void   sds_file__free_unpacked
                     (SdsFile *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_file__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_count__init
                     (ReadCount         *message)
{
  static ReadCount init_value = READ_COUNT__INIT;
  *message = init_value;
}
size_t read_count__get_packed_size
                     (const ReadCount *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_count__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_count__pack
                     (const ReadCount *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_count__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_count__pack_to_buffer
                     (const ReadCount *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_count__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadCount *
       read_count__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadCount *)
     protobuf_c_message_unpack (&read_count__descriptor,
                                allocator, len, data);
}
void   read_count__free_unpacked
                     (ReadCount *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &read_count__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   h5_hyperslab__init
                     (H5Hyperslab         *message)
{
  static H5Hyperslab init_value = H5_HYPERSLAB__INIT;
  *message = init_value;
}
size_t h5_hyperslab__get_packed_size
                     (const H5Hyperslab *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_hyperslab__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t h5_hyperslab__pack
                     (const H5Hyperslab *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_hyperslab__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t h5_hyperslab__pack_to_buffer
                     (const H5Hyperslab *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_hyperslab__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
H5Hyperslab *
       h5_hyperslab__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (H5Hyperslab *)
     protobuf_c_message_unpack (&h5_hyperslab__descriptor,
                                allocator, len, data);
}
void   h5_hyperslab__free_unpacked
                     (H5Hyperslab *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_hyperslab__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   h5_eselection__init
                     (H5Eselection         *message)
{
  static H5Eselection init_value = H5_ESELECTION__INIT;
  *message = init_value;
}
size_t h5_eselection__get_packed_size
                     (const H5Eselection *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_eselection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t h5_eselection__pack
                     (const H5Eselection *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_eselection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t h5_eselection__pack_to_buffer
                     (const H5Eselection *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_eselection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
H5Eselection *
       h5_eselection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (H5Eselection *)
     protobuf_c_message_unpack (&h5_eselection__descriptor,
                                allocator, len, data);
}
void   h5_eselection__free_unpacked
                     (H5Eselection *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &h5_eselection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   layout_metadata_t__init
                     (LayoutMetadataT         *message)
{
  static LayoutMetadataT init_value = LAYOUT_METADATA_T__INIT;
  *message = init_value;
}
size_t layout_metadata_t__get_packed_size
                     (const LayoutMetadataT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &layout_metadata_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t layout_metadata_t__pack
                     (const LayoutMetadataT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &layout_metadata_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t layout_metadata_t__pack_to_buffer
                     (const LayoutMetadataT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &layout_metadata_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LayoutMetadataT *
       layout_metadata_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LayoutMetadataT *)
     protobuf_c_message_unpack (&layout_metadata_t__descriptor,
                                allocator, len, data);
}
void   layout_metadata_t__free_unpacked
                     (LayoutMetadataT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &layout_metadata_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sds_metadata_db_value__init
                     (SDSMetadataDbValue         *message)
{
  static SDSMetadataDbValue init_value = SDS_METADATA_DB_VALUE__INIT;
  *message = init_value;
}
size_t sds_metadata_db_value__get_packed_size
                     (const SDSMetadataDbValue *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sds_metadata_db_value__pack
                     (const SDSMetadataDbValue *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sds_metadata_db_value__pack_to_buffer
                     (const SDSMetadataDbValue *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SDSMetadataDbValue *
       sds_metadata_db_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SDSMetadataDbValue *)
     protobuf_c_message_unpack (&sds_metadata_db_value__descriptor,
                                allocator, len, data);
}
void   sds_metadata_db_value__free_unpacked
                     (SDSMetadataDbValue *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sds_metadata_db_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sds_metadata_db_key__field_descriptors[5] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbKey, filename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbKey, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dsetname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbKey, dsetname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datatype",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbKey, datatype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filetype",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbKey, filetype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sds_metadata_db_key__field_indices_by_name[] = {
  3,   /* field[3] = datatype */
  2,   /* field[2] = dsetname */
  0,   /* field[0] = filename */
  4,   /* field[4] = filetype */
  1,   /* field[1] = group */
};
static const ProtobufCIntRange sds_metadata_db_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sds_metadata_db_key__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SDS_metadata_db_key",
  "SDSMetadataDbKey",
  "SDSMetadataDbKey",
  "",
  sizeof(SDSMetadataDbKey),
  5,
  sds_metadata_db_key__field_descriptors,
  sds_metadata_db_key__field_indices_by_name,
  1,  sds_metadata_db_key__number_ranges,
  (ProtobufCMessageInit) sds_metadata_db_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sds_file__field_descriptors[10] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, filename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, group),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dsetname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, dsetname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filetype",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, filetype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datatype",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, datatype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ir_type",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, ir_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cores",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SdsFile, has_cores),
    PROTOBUF_C_OFFSETOF(SdsFile, cores),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameters",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SdsFile, parameters),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_time",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SdsFile, has_create_time),
    PROTOBUF_C_OFFSETOF(SdsFile, create_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "io_pattern_type",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(SdsFile, has_io_pattern_type),
    PROTOBUF_C_OFFSETOF(SdsFile, io_pattern_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sds_file__field_indices_by_name[] = {
  6,   /* field[6] = cores */
  8,   /* field[8] = create_time */
  4,   /* field[4] = datatype */
  2,   /* field[2] = dsetname */
  0,   /* field[0] = filename */
  3,   /* field[3] = filetype */
  1,   /* field[1] = group */
  9,   /* field[9] = io_pattern_type */
  5,   /* field[5] = ir_type */
  7,   /* field[7] = parameters */
};
static const ProtobufCIntRange sds_file__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor sds_file__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sds_file",
  "SdsFile",
  "SdsFile",
  "",
  sizeof(SdsFile),
  10,
  sds_file__field_descriptors,
  sds_file__field_indices_by_name,
  1,  sds_file__number_ranges,
  (ProtobufCMessageInit) sds_file__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_count__field_descriptors[5] =
{
  {
    "interval_count",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReadCount, interval_count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_interval",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReadCount, previous_interval),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_400_interval",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReadCount, previous_400_interval),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_10000_interval",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReadCount, previous_10000_interval),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "life_time",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReadCount, life_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_count__field_indices_by_name[] = {
  0,   /* field[0] = interval_count */
  4,   /* field[4] = life_time */
  3,   /* field[3] = previous_10000_interval */
  2,   /* field[2] = previous_400_interval */
  1,   /* field[1] = previous_interval */
};
static const ProtobufCIntRange read_count__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor read_count__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "read_count",
  "ReadCount",
  "ReadCount",
  "",
  sizeof(ReadCount),
  5,
  read_count__field_descriptors,
  read_count__field_indices_by_name,
  1,  read_count__number_ranges,
  (ProtobufCMessageInit) read_count__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor h5_hyperslab__field_descriptors[4] =
{
  {
    "start",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(H5Hyperslab, n_start),
    PROTOBUF_C_OFFSETOF(H5Hyperslab, start),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stride",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(H5Hyperslab, n_stride),
    PROTOBUF_C_OFFSETOF(H5Hyperslab, stride),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(H5Hyperslab, n_count),
    PROTOBUF_C_OFFSETOF(H5Hyperslab, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(H5Hyperslab, n_block),
    PROTOBUF_C_OFFSETOF(H5Hyperslab, block),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned h5_hyperslab__field_indices_by_name[] = {
  3,   /* field[3] = block */
  2,   /* field[2] = count */
  0,   /* field[0] = start */
  1,   /* field[1] = stride */
};
static const ProtobufCIntRange h5_hyperslab__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor h5_hyperslab__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "h5_hyperslab",
  "H5Hyperslab",
  "H5Hyperslab",
  "",
  sizeof(H5Hyperslab),
  4,
  h5_hyperslab__field_descriptors,
  h5_hyperslab__field_indices_by_name,
  1,  h5_hyperslab__number_ranges,
  (ProtobufCMessageInit) h5_hyperslab__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor h5_eselection__field_descriptors[1] =
{
  {
    "coordination",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(H5Eselection, n_coordination),
    PROTOBUF_C_OFFSETOF(H5Eselection, coordination),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned h5_eselection__field_indices_by_name[] = {
  0,   /* field[0] = coordination */
};
static const ProtobufCIntRange h5_eselection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor h5_eselection__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "h5_eselection",
  "H5Eselection",
  "H5Eselection",
  "",
  sizeof(H5Eselection),
  1,
  h5_eselection__field_descriptors,
  h5_eselection__field_indices_by_name,
  1,  h5_eselection__number_ranges,
  (ProtobufCMessageInit) h5_eselection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor layout_metadata_t__field_descriptors[10] =
{
  {
    "pattern_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, pattern_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_global_start",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, n_req_global_start),
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, req_global_start),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_global_end",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, n_req_global_end),
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, req_global_end),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_hyperslab",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, n_req_hyperslab),
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, req_hyperslab),
    &h5_hyperslab__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_element",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, req_element),
    &h5_eselection__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opt_file",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, opt_file),
    &sds_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opt_file_status",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, opt_file_status),
    &file_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opt_hyperslab",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, n_opt_hyperslab),
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, opt_hyperslab),
    &h5_hyperslab__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linear_order",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, linear_order),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chunk_size",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, n_chunk_size),
    PROTOBUF_C_OFFSETOF(LayoutMetadataT, chunk_size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned layout_metadata_t__field_indices_by_name[] = {
  9,   /* field[9] = chunk_size */
  8,   /* field[8] = linear_order */
  5,   /* field[5] = opt_file */
  6,   /* field[6] = opt_file_status */
  7,   /* field[7] = opt_hyperslab */
  0,   /* field[0] = pattern_type */
  4,   /* field[4] = req_element */
  2,   /* field[2] = req_global_end */
  1,   /* field[1] = req_global_start */
  3,   /* field[3] = req_hyperslab */
};
static const ProtobufCIntRange layout_metadata_t__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor layout_metadata_t__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "layout_metadata_t",
  "LayoutMetadataT",
  "LayoutMetadataT",
  "",
  sizeof(LayoutMetadataT),
  10,
  layout_metadata_t__field_descriptors,
  layout_metadata_t__field_indices_by_name,
  1,  layout_metadata_t__number_ranges,
  (ProtobufCMessageInit) layout_metadata_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sds_metadata_db_value__field_descriptors[12] =
{
  {
    "index_file_status",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, n_index_file_status),
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, index_file_status),
    &file_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index_files",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, n_index_files),
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, index_files),
    &sds_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reorg_file_status",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, n_reorg_file_status),
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, reorg_file_status),
    &file_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reorg_files",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, n_reorg_files),
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, reorg_files),
    &sds_file__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_count",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, read_count),
    &read_count__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner_id",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, owner_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_id",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, group_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner_bit",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, owner_bit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_bit",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, group_bit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_bit",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, other_bit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orig_file_status",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, orig_file_status),
    &file_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "layout_metadata",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, n_layout_metadata),
    PROTOBUF_C_OFFSETOF(SDSMetadataDbValue, layout_metadata),
    &layout_metadata_t__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sds_metadata_db_value__field_indices_by_name[] = {
  8,   /* field[8] = group_bit */
  6,   /* field[6] = group_id */
  0,   /* field[0] = index_file_status */
  1,   /* field[1] = index_files */
  11,   /* field[11] = layout_metadata */
  10,   /* field[10] = orig_file_status */
  9,   /* field[9] = other_bit */
  7,   /* field[7] = owner_bit */
  5,   /* field[5] = owner_id */
  4,   /* field[4] = read_count */
  2,   /* field[2] = reorg_file_status */
  3,   /* field[3] = reorg_files */
};
static const ProtobufCIntRange sds_metadata_db_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor sds_metadata_db_value__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SDS_metadata_db_value",
  "SDSMetadataDbValue",
  "SDSMetadataDbValue",
  "",
  sizeof(SDSMetadataDbValue),
  12,
  sds_metadata_db_value__field_descriptors,
  sds_metadata_db_value__field_indices_by_name,
  1,  sds_metadata_db_value__number_ranges,
  (ProtobufCMessageInit) sds_metadata_db_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue file_status__enum_values_by_number[2] =
{
  { "IN_SERVICE", "FILE_STATUS__IN_SERVICE", 0 },
  { "NOT_IN_SERVICE", "FILE_STATUS__NOT_IN_SERVICE", 1 },
};
static const ProtobufCIntRange file_status__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex file_status__enum_values_by_name[2] =
{
  { "IN_SERVICE", 0 },
  { "NOT_IN_SERVICE", 1 },
};
const ProtobufCEnumDescriptor file_status__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "file_status",
  "file_status",
  "FileStatus",
  "",
  2,
  file_status__enum_values_by_number,
  2,
  file_status__enum_values_by_name,
  1,
  file_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
